apiVersion: v1
kind: ReplicationController
metadata:
  name: spring-controller
spec:
  replicas: 9
  selector:
    name: springboot
  template:
    metadata:
      labels:
        name: springboot
    spec:
      containers:
      - image: tiger5559/spring-boot-mongo:${BUILD_NUMBER}
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: springboot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: springboot
